name: Continuous Integration
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  automation-test-job:
    name: automation-test-job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: npm install -g pnpm
      - name: pnpm install and test
        run: |
          pnpm install
          pnpx cypress install
          pnpm run ci:test